### PR TITLE
Bump Jest version for node v0.12 support.

### PR DESCRIPTION
**Pull request by SupremeTechnopriest**
Bump Jest version for node v0.12 support.

https://github.com/facebook/jest/pull/261

### CODE REVIEW

**Comment by SupremeTechnopriest** [comment]
as @ncuillery said, this pull request will also solve #9

**Comment by SupremeTechnopriest** [comment]
@Dakuan: Any way we can get this merged, bumped and published?

**Comment by Dakuan** [comment]
done!

**Comment by SupremeTechnopriest** [comment]
Thank you!

**Pull request merged**
